[top_level]
module = "module ${1:name} (${2:ports});\n\t${0}\nendmodule"
primitive = "primitive ${1:name} (${2:ports});\n\t${0}\nendprimitive"
macromodule = "macromodule ${1:name} (${2:ports});\n\t${0}\nendmodule"

[module_item]
wire = "wire ${1:name};"
reg = "reg ${1:name};"
tri = "tri ${1:name};"
tri0 = "tri0 ${1:name};"
tri1 = "tri1 ${1:name};"
trireg = "trireg ${1:name};"
triand = "triand ${1:name};"
trior = "trior ${1:name};"
wand = "wand ${1:name};"
wor = "wor ${1:name};"
supply0 = "supply0 ${1:name};"
supply1 = "supply1 ${1:name};"
integer = "integer ${1:name};"
real = "real ${1:name};"
realtime = "realtime ${1:name};"
time = "time ${1:name};"
event = "event ${1:name};"
parameter = "parameter ${1:NAME} = ${2:VALUE};"
localparam = "localparam ${1:NAME} = ${2:VALUE};"
specparam = "specparam ${1:NAME} = ${2:VALUE};"
defparam = "defparam ${1:path} = ${2:value};"
genvar = "genvar ${1:i};"
generate = "generate\n\t${0}\nendgenerate"
function = "function ${1:name};\n\t${0}\nendfunction"
task = "task ${1:name};\n\t${0}\nendtask"
assign = "assign ${1:lhs} = ${0:rhs};"
deassign = "deassign ${1:lhs};"
force = "force ${1:lhs} = ${0:rhs};"
release = "release ${1:lhs};"
always = "always ${1} begin\n\t${0}\nend"
"always @(*)" = { plain = "always", snippet = "always @(*) begin\n\t${0}\nend" }
initial = "initial begin\n\t${0}\nend"
begin = "begin\n\t${0}\nend"
fork = "fork\n\t${0}\njoin"
if = "if (${1:cond}) begin\n\t${0}\nend"
ifelse = { plain = "if", snippet = "if (${1:cond}) begin\n\t${2}\nend else begin\n\t${0}\nend" }
case = "case (${1:expr})\n\t${2:val}: ${3:stmt};\n\tdefault: ${0:stmt};\nendcase"
casez = "casez (${1:expr})\n\t${2:val}: ${3:stmt};\n\tdefault: ${0:stmt};\nendcase"
casex = "casex (${1:expr})\n\t${2:val}: ${3:stmt};\n\tdefault: ${0:stmt};\nendcase"
for = "for (${1:i} = ${2:0}; ${3:i} < ${4:N}; ${5:i} = ${6:i} + 1) begin\n\t${0}\nend"
while = "while (${1:cond}) begin\n\t${0}\nend"
repeat = "repeat (${1:N}) begin\n\t${0}\nend"
forever = "forever begin\n\t${0}\nend"
disable = "disable ${1:block};"
wait = "wait (${1:cond}) begin\n\t${0}\nend"
specify = "specify\n\t${0}\nendspecify"
