#![recursion_limit = "512"]

use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};

const VSCODE_SCHEMA_CONSTANTS_PATH: &str = "editors/vscode/src/generated/projectConfigSchema.ts";
const USER_CONFIG_SCHEMA_PATH: &str = "/schemas/v1/user-config.schema.json";

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    let Some(command) = args.next() else {
        print_help();
        return Ok(());
    };

    if args.next().is_some() {
        bail!("unexpected extra arguments");
    }

    match command.as_str() {
        "generate-schemas" | "generate-manifest-schema" => write_schemas(&workspace_root()?),
        "check-schemas" | "check-manifest-schema" => check_schemas(&workspace_root()?),
        "-h" | "--help" | "help" => {
            print_help();
            Ok(())
        }
        _ => bail!("unknown xtask command: {command}"),
    }
}

fn print_help() {
    eprintln!("Usage: cargo xtask <command>\n\nCommands:\n  generate-schemas\n  check-schemas");
}

fn workspace_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .context("xtask manifest directory has no parent")
}

fn checked_in_manifest_schema_path(workspace_root: &Path) -> PathBuf {
    workspace_root.join(project_model::TOML_MANIFEST_SCHEMA_PATH.trim_start_matches('/'))
}

fn checked_in_user_config_schema_path(workspace_root: &Path) -> PathBuf {
    workspace_root.join(USER_CONFIG_SCHEMA_PATH.trim_start_matches('/'))
}

fn vscode_schema_constants_path(workspace_root: &Path) -> PathBuf {
    workspace_root.join(VSCODE_SCHEMA_CONSTANTS_PATH)
}

fn generated_manifest_schema() -> serde_json::Value {
    project_model::generated_toml_manifest_schema()
}

fn generated_manifest_schema_text() -> Result<String> {
    let generated = generated_manifest_schema();
    Ok(format!("{}\n", serde_json::to_string_pretty(&generated)?))
}

fn user_config_schema_text() -> Result<String> {
    let schema = vide::generated_user_config_schema();
    Ok(format!("{}\n", serde_json::to_string_pretty(&schema)?))
}

fn generated_vscode_schema_constants_text() -> Result<String> {
    let version = serde_json::to_string(project_model::TOML_MANIFEST_SCHEMA_VERSION)?;
    let path = serde_json::to_string(project_model::TOML_MANIFEST_SCHEMA_PATH)?;
    let url = serde_json::to_string(project_model::TOML_MANIFEST_SCHEMA_URL)?;

    Ok(format!(
        "// Generated by `cargo xtask generate-schemas`; do not edit.\n\
         export const PROJECT_CONFIG_SCHEMA_VERSION = {version};\n\
         export const PROJECT_CONFIG_SCHEMA_PATH = {path};\n\
         export const PROJECT_CONFIG_SCHEMA_URL = {url};\n"
    ))
}

fn write_schemas(workspace_root: &Path) -> Result<()> {
    let manifest_schema = generated_manifest_schema_text()?;
    let user_config_schema = user_config_schema_text()?;

    write_generated_file(&checked_in_manifest_schema_path(workspace_root), &manifest_schema)?;
    write_generated_file(&checked_in_user_config_schema_path(workspace_root), &user_config_schema)?;
    write_generated_file(
        &vscode_schema_constants_path(workspace_root),
        &generated_vscode_schema_constants_text()?,
    )?;
    Ok(())
}

fn check_schemas(workspace_root: &Path) -> Result<()> {
    let manifest_schema = generated_manifest_schema_text()?;
    let user_config_schema = user_config_schema_text()?;

    check_file_matches(&checked_in_manifest_schema_path(workspace_root), &manifest_schema)?;
    check_file_matches(&checked_in_user_config_schema_path(workspace_root), &user_config_schema)?;
    check_file_matches(
        &vscode_schema_constants_path(workspace_root),
        &generated_vscode_schema_constants_text()?,
    )?;

    Ok(())
}

fn write_generated_file(path: &Path, contents: &str) -> Result<()> {
    let Some(parent) = path.parent() else {
        bail!("generated file path has no parent: {}", path.display());
    };

    fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))?;
    eprintln!("wrote {}", path.display());
    Ok(())
}

fn check_file_matches(path: &Path, expected: &str) -> Result<()> {
    let checked_in =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;

    if checked_in != expected {
        bail!("{} is stale; run `cargo xtask generate-schemas`", path.display());
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_schemas_match_generated_schemas() {
        check_schemas(&workspace_root().unwrap()).unwrap();
    }
}
