name: Release

on:
  push:
    tags:
      - "v*"
      - "nightly"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-package:
    name: Build & Package VS Code Extension
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: ubuntu-latest
            target: linux-arm64
          - os: windows-latest
            target: win32-x64
          - os: windows-latest
            target: win32-arm64
          - os: macos-latest
            target: darwin-x64
          - os: macos-latest
            target: darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target == 'linux-arm64' && 'aarch64-unknown-linux-gnu' || matrix.target == 'darwin-arm64' && 'aarch64-apple-darwin' || matrix.target == 'win32-arm64' && 'aarch64-pc-windows-msvc' || '' }}
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install JS dependencies
        working-directory: editors/vscode
        run: pnpm install --frozen-lockfile

      - name: Package Extension
        working-directory: editors/vscode
        run: pnpm run package:${{ matrix.target }}
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vizsla-${{ matrix.target }}.vsix
          path: editors/vscode/*.vsix

  publish:
    name: Publish Release
    needs: [build-and-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ github.ref_name == 'nightly' }}
          files: artifacts/**/*.vsix
